steps:
   - name: gcr.io/cloud-builders/git
     args: ["fetch"]
     dir: "git/TestCICD"
   - name: gcr.io/cloud-builders/git
     args: ["checkout",  "main"]
     dir: "git/TestCICD"
   - name: gcr.io/cloud-builders/git
     args: [
            "-c",
            'user.name="dhanap14"',
            "-c",
            'user.email="dhanasekar.paramasivam@labor.ny.gov"',
            "merge", 
            "origin/SecondBranch",
            "--allow-unrelated-histories"]
     dir: "git/TestCICD"
   - name: gcr.io/cloud-builders/git
     args: ["push", 'https://fake_user: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@github.com/dhanap14/TestCICD.git', "origin/main"]
     dir: "git/TestCICD"
