steps:
#   - name: gcr.io/cloud-builders/git
#     args: ["fetch"]
#     dir: "git/TestCICD"
#     env:
#       - "GH_TOKEN=$_GH_TOKEN"
       
   - name: gcr.io/cloud-builders/git
     args: ["checkout",  "origin/main"]
     dir: "git/TestCICD"
     
   - name: gcr.io/cloud-builders/git
     args: ["pull"]
     dir: "git/TestCICD"
     
   - name: gcr.io/cloud-builders/git
     args: [
            "-c",
            'user.name="dhanap14"',
            "-c",
            'user.email="dhanasekar.paramasivam@labor.ny.gov"',
            "merge", 
            "origin/SecondBranch",
            "--allow-unrelated-histories"]
     dir: "git/TestCICD"
     
   - name: gcr.io/cloud-builders/git
     args: ["push", 'https://fake_user:$_GH_TOKEN@github.com/dhanap14/TestCICD.git']
     dir: "git/TestCICD"
