steps:
   - name: gcr.io/cloud-builders/git
     args: ["fetch"]
     dir: "git/TestCICD"
   - name: gcr.io/cloud-builders/git
     args: ["checkout",  "SecondBranch"]
     dir: "git/TestCICD"
   - name: "gcr.io/cloud-builders/git"
     args: [
            "-c",
            'user.name="dhanap14"',
            "-c",
            'user.email="dhanasekar.paramasivam@labor.ny.gov"',
            "merge", 
            "origin/main",
            "--allow-unrelated-histories"]
     dir: "git/TestCICD"
