steps:
   - name: gcr.io/cloud-builders/git
     args: ["checkout", "origin", "main"]
     dir: "git/TestCICD"
   - name: "gcr.io/cloud-builders/git"
     args: ["merge", "SecondBranch"]
     dir: "git/TestCICD"
