steps:
- name: 'docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/helloworld-image', '.' ]

# By default, all built docker images will be lost once the build is complete.
# Rather than writing a build step to push this image, you can simply list the
# image below and it will automatically be uploaded to Google Cloud Container
# Registry.
images:
- 'gcr.io/$PROJECT_ID/helloworld-image'

# You can organize your builds with tags
tags: ['gcp-cloud-build-sample-build']
- name: 'gke-deploy'
  args:
  - run
  - --filename=helloworld-image
  - --image=gcr.io/dol-uim-devops/helloworld-image@sha256:450d94b7eb9b8c44b0001e7475d7d47c97e42b0066c099ae208cadbc4b994e0e:latest
  - --location=${_CLOUDSDK_COMPUTE_ZONE}
  - --cluster=${_CLOUDSDK_CONTAINER_CLUSTER}
